//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFreeTime.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEightBall")]
    public interface IEightBall {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/GetAnswerForQuestion", ReplyAction="http://tempuri.org/IEightBall/GetAnswerForQuestionResponse")]
        string GetAnswerForQuestion(string qeustion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEightBall/GetAnswerForQuestion", ReplyAction="http://tempuri.org/IEightBall/GetAnswerForQuestionResponse")]
        System.Threading.Tasks.Task<string> GetAnswerForQuestionAsync(string qeustion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEightBallChannel : MyFreeTime.ServiceReference1.IEightBall, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EightBallClient : System.ServiceModel.ClientBase<MyFreeTime.ServiceReference1.IEightBall>, MyFreeTime.ServiceReference1.IEightBall {
        
        public EightBallClient() {
        }
        
        public EightBallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EightBallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EightBallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAnswerForQuestion(string qeustion) {
            return base.Channel.GetAnswerForQuestion(qeustion);
        }
        
        public System.Threading.Tasks.Task<string> GetAnswerForQuestionAsync(string qeustion) {
            return base.Channel.GetAnswerForQuestionAsync(qeustion);
        }
    }
}
